# Generated by Django 3.2 on 2022-11-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='id',
            new_name='identificador',
        ),
    ]
