# Generated by Django 3.2 on 2022-11-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_auto_20221125_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre Completo'),
        ),
    ]
