# Generated by Django 3.2 on 2022-11-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_cliente_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido de cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(max_length=50, verbose_name='Nombre Completo'),
        ),
    ]
