# Generated by Django 3.2 on 2022-11-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_auto_20221127_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(max_length=50, verbose_name='<django.db.models.fields.CharField> <django.db.models.fields.CharField>'),
        ),
    ]
