# Generated by Django 3.2 on 2022-11-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_alter_cliente_nombre_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_completo',
        ),
    ]
