# Generated by Django 3.2 on 2022-11-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0006_remove_cliente_nombre_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre Completo'),
        ),
    ]
