# Generated by Django 3.2 on 2022-12-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0007_cliente_nombre_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='Cliente', verbose_name='imagen'),
        ),
    ]
