# Generated by Django 3.2 on 2022-12-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0008_cliente_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='Cliente', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
