# Generated by Django 3.2 on 2022-11-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id',
            new_name='identificador',
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
        ),
    ]
