# Generated by Django 3.2 on 2022-11-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_alter_marca_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
    ]
