# Generated by Django 3.2 on 2022-12-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_alter_marca_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marcaProd',
        ),
        migrations.AddField(
            model_name='producto',
            name='marcaProd',
            field=models.ManyToManyField(to='Producto.Marca'),
        ),
    ]
