# Generated by Django 3.2 on 2022-12-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0006_producto_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='marcaProd',
            new_name='marca',
        ),
    ]
