# Generated by Django 3.2 on 2022-12-05 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0002_rename_id_proveedor_identificador'),
        ('Producto', '0007_rename_marcaprod_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor'),
        ),
    ]
